/*-
 * Copyright (c) 2018-2020 Ruslan Bukin <br@bsdpad.com>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

#ifndef _ARM64_ROCKCHIP_RK3399_HDMI_H_
#define _ARM64_ROCKCHIP_RK3399_HDMI_H_

#define	GRF_SOC_CON20	0x6250
#define	 CON20_DSI0_VOP_SEL_S	0
#define	 CON20_DSI0_VOP_SEL_M	(1 << CON20_DSI0_VOP_SEL_S)
#define	 CON20_DSI0_VOP_SEL_B	(0 << CON20_DSI0_VOP_SEL_S)
#define	 CON20_DSI0_VOP_SEL_L	(1 << CON20_DSI0_VOP_SEL_S)
#define	 CON20_HDMI_VOP_SEL_S	6
#define	 CON20_HDMI_VOP_SEL_M	(1 << CON20_HDMI_VOP_SEL_S)
#define	 CON20_HDMI_VOP_SEL_B	(0 << CON20_HDMI_VOP_SEL_S)
#define	 CON20_HDMI_VOP_SEL_L	(1 << CON20_HDMI_VOP_SEL_S)

#define	GRF_SOC_CON22	0x6258
#define	 CON22_DPHY_TX0_RXMODE_S	0
#define	 CON22_DPHY_TX0_RXMODE_M	(0xf << CON22_DPHY_TX0_RXMODE_S)
#define	 CON22_DPHY_TX0_RXMODE_EN	(0xb << CON22_DPHY_TX0_RXMODE_S)
#define	 CON22_DPHY_TX0_RXMODE_DIS	(0x0 << CON22_DPHY_TX0_RXMODE_S)
#define	 CON22_DPHY_TX0_TXSTOPMODE_S	4
#define	 CON22_DPHY_TX0_TXSTOPMODE_M	(0xf << CON22_DPHY_TX0_TXSTOPMODE_S)
#define	 CON22_DPHY_TX0_TXSTOPMODE_EN	(0xc << CON22_DPHY_TX0_TXSTOPMODE_S)
#define	 CON22_DPHY_TX0_TXSTOPMODE_DIS	(0x0 << CON22_DPHY_TX0_TXSTOPMODE_S)
#define	 CON22_DPHY_TX0_TURNREQUEST_S	12
#define	 CON22_DPHY_TX0_TURNREQUEST_M	(0xf << CON22_DPHY_TX0_TURNREQUEST_S)
#define	 CON22_DPHY_TX0_TURNREQUEST_EN	(0x1 << CON22_DPHY_TX0_TURNREQUEST_S)
#define	 CON22_DPHY_TX0_TURNREQUEST_DIS	(0x0 << CON22_DPHY_TX0_TURNREQUEST_S)

#endif /* !_ARM64_ROCKCHIP_RK3399_HDMI_H_ */
