/*-
 * Copyright (c) 2018-2020 Ruslan Bukin <br@bsdpad.com>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

#ifndef _ARM64_ROCKCHIP_RK3399_HDMI_H_
#define _ARM64_ROCKCHIP_RK3399_HDMI_H_

/* PHY Configuration Registers */
#define	HDMI_PHY_CONF0		0x3000
#define	HDMI_PHY_TST0		0x3001
#define	HDMI_PHY_TST1		0x3002
#define	HDMI_PHY_TST2		0x3003
#define	HDMI_PHY_STAT0		0x3004
#define	 PHY_STAT0_HPD		(1 << 1) /* HDMI Hot Plug Detect indication */
#define	HDMI_PHY_INT0		0x3005
#define	HDMI_PHY_MASK0		0x3006
#define	HDMI_PHY_POL0		0x3007

#define	HDMI_PHY_I2CM_SLAVE			0x3020
#define	HDMI_PHY_I2CM_ADDRESS			0x3021
#define	HDMI_PHY_I2CM_DATAO_1			0x3022
#define	HDMI_PHY_I2CM_DATAO_0			0x3023
#define	HDMI_PHY_I2CM_DATAI_1			0x3024
#define	HDMI_PHY_I2CM_DATAI_0			0x3025
#define	HDMI_PHY_I2CM_OPERATION			0x3026
#define	HDMI_PHY_I2CM_INT			0x3027
#define	 PHY_I2CM_INT_DONE_M			(1 << 2)
#define	HDMI_PHY_I2CM_CTLINT			0x3028
#define	 PHY_I2CM_CTLINT_NACK_M			(1 << 6)
#define	 PHY_I2CM_CTLINT_ARBITRATION_M		(1 << 2)
#define	HDMI_PHY_I2CM_DIV			0x3029
#define	HDMI_PHY_I2CM_SOFTRSTZ			0x302a
#define	HDMI_PHY_I2CM_SS_SCL_HCNT_1_ADDR	0x302b
#define	HDMI_PHY_I2CM_SS_SCL_HCNT_0_ADDR	0x302c
#define	HDMI_PHY_I2CM_SS_SCL_LCNT_1_ADDR	0x302d
#define	HDMI_PHY_I2CM_SS_SCL_LCNT_0_ADDR	0x302e
#define	HDMI_PHY_I2CM_FS_SCL_HCNT_1_ADDR	0x302f
#define	HDMI_PHY_I2CM_FS_SCL_HCNT_0_ADDR	0x3030
#define	HDMI_PHY_I2CM_FS_SCL_LCNT_1_ADDR	0x3031
#define	HDMI_PHY_I2CM_FS_SCL_LCNT_0_ADDR	0x3032
#define	HDMI_PHY_I2CM_SDA_HOLD			0x3033

/* Interrupt Registers */
#define	HDMI_IH_FC_STAT0			0x100
#define	HDMI_IH_FC_STAT1			0x101
#define	HDMI_IH_FC_STAT2			0x102
#define	HDMI_IH_AS_STAT0			0x103
#define	HDMI_IH_PHY_STAT0			0x104
#define	HDMI_IH_I2CM_STAT0			0x105
#define	HDMI_IH_CEC_STAT0			0x106
#define	HDMI_IH_VP_STAT0			0x107
#define	HDMI_IH_I2CMPHY_STAT0			0x108
#define	HDMI_IH_AHBDMAAUD_STAT0			0x109
#define	HDMI_IH_DECODE				0x170
#define	HDMI_IH_MUTE_FC_STAT0			0x180
#define	HDMI_IH_MUTE_FC_STAT1			0x181
#define	HDMI_IH_MUTE_FC_STAT2			0x182
#define	HDMI_IH_MUTE_AS_STAT0			0x183
#define	HDMI_IH_MUTE_PHY_STAT0			0x184
#define	HDMI_IH_MUTE_I2CM_STAT0			0x185
#define	HDMI_IH_MUTE_CEC_STAT0			0x186
#define	HDMI_IH_MUTE_VP_STAT0			0x187
#define	HDMI_IH_MUTE_I2CMPHY_STAT0		0x188
#define	HDMI_IH_MUTE_AHBDMAAUD_STAT0		0x189
#define	HDMI_IH_MUTE				0x1FF
#define	 IH_MUTE_WAKEUP_INTERRUPT		(1 << 1)
#define	 IH_MUTE_ALL_INTERRUPT			(1 << 0)

#define	GRF_SOC_CON20	0x6250
#define	 CON20_DSI0_VOP_SEL_S	0
#define	 CON20_DSI0_VOP_SEL_M	(1 << CON20_DSI0_VOP_SEL_S)
#define	 CON20_DSI0_VOP_SEL_B	(0 << CON20_DSI0_VOP_SEL_S)
#define	 CON20_DSI0_VOP_SEL_L	(1 << CON20_DSI0_VOP_SEL_S)
#define	 CON20_HDMI_VOP_SEL_S	6
#define	 CON20_HDMI_VOP_SEL_M	(1 << CON20_HDMI_VOP_SEL_S)
#define	 CON20_HDMI_VOP_SEL_B	(0 << CON20_HDMI_VOP_SEL_S)
#define	 CON20_HDMI_VOP_SEL_L	(1 << CON20_HDMI_VOP_SEL_S)

#define	GRF_SOC_CON22	0x6258
#define	 CON22_DPHY_TX0_RXMODE_S	0
#define	 CON22_DPHY_TX0_RXMODE_M	(0xf << CON22_DPHY_TX0_RXMODE_S)
#define	 CON22_DPHY_TX0_RXMODE_EN	(0xb << CON22_DPHY_TX0_RXMODE_S)
#define	 CON22_DPHY_TX0_RXMODE_DIS	(0x0 << CON22_DPHY_TX0_RXMODE_S)
#define	 CON22_DPHY_TX0_TXSTOPMODE_S	4
#define	 CON22_DPHY_TX0_TXSTOPMODE_M	(0xf << CON22_DPHY_TX0_TXSTOPMODE_S)
#define	 CON22_DPHY_TX0_TXSTOPMODE_EN	(0xc << CON22_DPHY_TX0_TXSTOPMODE_S)
#define	 CON22_DPHY_TX0_TXSTOPMODE_DIS	(0x0 << CON22_DPHY_TX0_TXSTOPMODE_S)
#define	 CON22_DPHY_TX0_TURNREQUEST_S	12
#define	 CON22_DPHY_TX0_TURNREQUEST_M	(0xf << CON22_DPHY_TX0_TURNREQUEST_S)
#define	 CON22_DPHY_TX0_TURNREQUEST_EN	(0x1 << CON22_DPHY_TX0_TURNREQUEST_S)
#define	 CON22_DPHY_TX0_TURNREQUEST_DIS	(0x0 << CON22_DPHY_TX0_TURNREQUEST_S)

#endif /* !_ARM64_ROCKCHIP_RK3399_HDMI_H_ */
